version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'admin']
      timeout: 10s
      retries: 5
